############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Über mich"
url = "/about"
weight = 2

# [[main]]
# name = "Elements"
# url = "/elements"
# weight = 3

[[main]]
weight = 4
name = "Sonstiges"

[[main]]
parent = "Sonstiges"
name = "Blog"
# url = "/blog"
url = "https://blog.k4li.me/"

[[main]]
parent = "Sonstiges"
name = "Kontakt"
url = "/contact"

# [[main]]
# parent = "Sonstiges"
# name = "Authors"
# url = "/authors"

[[main]]
parent = "Sonstiges"
name = "Kategorien"
url = "/categories"

# [[main]]
# parent = "Sonstiges"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "Über mich"
url = "/about"
weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
